# Thought and Language

## Overview {-}

***Welcome to PSYC 106: Introduction to Psychology***

This course will examine many different aspects of behaviour - from microscopic internal structures and functions to group and social processes. Though this journey covers many topics, the central theme of our exploration will be to understand why, and how, we behave the way we do.
In Unit 1, we will start to explore how psychology can help you see the world in a different way and can help you understand why other people behave the way they do. One of the reasons psychology is such an exciting field is that it is easy to see how this field of study relates to your own life. You live out psychology; you feel emotions, you take in sensations, and you produce behaviours such as thoughts and actions. Additionally, human behaviour is complex and can be interpreted in numerous ways. Every topic in psychology could be examined from any one of these interdependent perspectives: biological, cognitive (thinking), and sociocultural (know as the biopsychosocial model). What is more is that for many people the spiritual perspective is an essential consideration, too. Therefore, to begin using psychology as a lens from which to understand behaviour it will be important for you to know what psychology is, what psychologists do, and how to critically evaluate your beliefs using the tools of psychological science.

### Topics {-}

This unit is divided into the following topics:

1. What is Psychology?
2. What Do Psychologists Do?
3. Thinking Critically with Psychological Science

### Learning Outcomes {-}

When you have completed this unit, you should be able to:

- Define the key terminology of the scientific method.  
- Define important historical terminology from the field of psychology.  
- Describe the steps of the scientific method, the concept of scientific literacy, and how various philosophical and scientific fields became major influences on psychology.  
- Apply the biopsychosocial model to behaviour, the steps in critical thinking, and your knowledge to distinguish among the different specializations in psychology.  
- Analyze the use of the term scientific theory and how the philosophical ideas of empiricism and determinism are applied to human behaviour.  


### Activity Checklist: {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

```{block2, type='reflect'}

<span class="blockhead">Learning Activities</span>

- Read and Reflect – Chapter 1  
- Review the Unit 1 – Course Notes (found on Course Notes tab)  
- Complete the Exploring Career Opportunities activity  
- Complete the Ethics in Psychology activity  
- Complete the Terminology Practice activity.  

```

```{block2, type='caution'}

***Note*** 
The course units follow topics in the textbook, Revel for An Introduction to Psychological Science by Krause et al. (4th Edition). For each unit, please read the pertinent chapter(s) before completing the assessment for the unit.

```

```{block2, type='assessment'}

<span class="blockhead">Assessment</span>

In this course you demonstrate your understanding of the course learning outcomes in different ways, including papers, projects, discussions and quizzes. Please see the Assessment section in Moodle for assignment details and due dates.

```

### Resources {-}

Here are the resources you will need to complete this unit:

- Krause, M., Corts, D., & Smith, S. C. (2024). Revel for An Introduction to Psychological Science, 4th Canadian Edition. Pearson Ed.  
- Other resources will be provided online.  

## What is Psychology

Before you read the textbook, write a brief definition of psychology. (Or if you’ve already read the textbook try to remember how you would have defined psychology before you read it.) According to your definition, how is psychology different from other academic areas that would study humans, for example philosophy, or literature, or history? If you said, “Psychology is different because it uses the scientific method,” give yourself a pat on the back.
Your textbook explains the scientific method.

The following simple parable from Philipchalk’s social psychology textbook illustrates three “helpful” approaches to a problem, including a simple experiment:

*Once upon a time there were three brothers. One day while they were working in their father’s field, they saw an old man coming along the road. The old man greeted them, and then struggled on along the road, limping terribly. After that, every day at the same time, the brothers greeted the old man and watched as he hobbled by. When a month had passed, they were so impressed that they each did something. The first brother wrote a compelling story about perseverance in the face of the ravages of old age. It encouraged many people. The second brother painted a moving portrait of the old man, stooped over and limping along. People were inspired. The third brother, who had observed the old man very closely, asked him one day if he could exchange shoes with him. The old man was surprised, but he gladly agreed. When the old man walked away he did not limp. The next day the third brother gave the old man his shoes back and watched as he limped on his way. On the third day, the brother again exchanged shoes with the old man. Then he took the old man’s shoes to a shoemaker and had them repaired. When the brother gave them back to the old man he was delighted. The old man put on the shoes, thanked the brother, and walked away without a limp.*

Although each brother made a positive contribution, the third brother solved the man’s problem because he discovered its cause. To do this, he used the scientific method and he conducted an experiment (Philipchalk, 1994).

I find psychology to be one of the most interesting areas of study for a number of reasons. First, because it is adventurous enough to study the complexities of people, and people like you and I are interesting. Second, I like the range of topics available to be studied in psychology - psychologists, as you will see, study everything from nerve conduction in single cells all the way to the influence of groups on our behaviour; anything a human does can be studied in this discipline. Finally, prudent psychologists suspend their speculations and opinions as they look for evidence for their ideas. If they do not find sufficient evidence, they have the humility to change their ideas. When growing in knowledge about topics not yet entirely understood, humility is essential. Now, let us return to the scientific method and how psychology began.

## How Did Psychology Begin? 

One definition of psychology is that it is the application of the scientific method to the questions of philosophy. With that hint in mind, how far back do you think we could trace the roots of psychology? You will find answers to this question in the textbook, and also at sites such as the following:

- Classics in the History of Psychology [https://psychclassics.yorku.ca/]{target="_blank”}  
- Psychology (for a history of psychology in Canada)[https://www.thecanadianencyclopedia.ca/en/article/psychology]{target="_blank”}  

A more basic, tongue-in-cheek, answer to the question is the following: The first person interested in psychology was either the first person trying to understand the first person or the second person who was trying to figure out the first person!

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

- What draws people to study psychology? (It is one of the most popular majors in North American universities).  
- What drew you to study psychology?  
- Some people argue that the scientific method is appropriate for studying inanimate objects and simple organisms but not appropriate for studying complex human behavior. What are the strengths and weaknesses of applying the scientific method to the study of people?  
- Some postmodernists argue that since complete objectivity is impossible, science is not an appropriate route to the understanding of human thought and behavior. How would you respond to this criticism?  

*Be prepared to share your thoughts and insights with other members of the class*

```

## What Do Psychologists Do? 

Ask most people to name two or three famous psychologists and one of the first named will be Sigmund Freud. This reflects the common idea that most psychologists try to analyze people and figure out underlying motives so that they can help to solve deep-seated problems. In fact, less than half of all psychologists work in clinical settings studying the causes, diagnoses, and treatment of mental disorders. Many psychologists study human development, learning, memory and other mental processes. Others conduct research on groups and social influence. Some psychologists work in schools, others in government, and still others in industry. All of these psychologists are either trying to understand people better, or trying to help them, or both.

For simplicity, the different ways of approaching psychology can be grouped into three broad categories:

- Those that focus on the physical, biological bases of behavior.  
- Those that concentrate on mental processes that control our actions.  
- Those that emphasize the external environmental influences on what we think and do.  

Which approach is best? The best approach is all of them. They all add something to our understanding of ourselves. It is best to see the many ways of studying human behavior as different perspectives rather than competing points of view. Like different perspectives on a landscape, they provide depth and dimensionality to our understanding. Why is Jenna blushing? From an external, environmental point of view we might say, “Because she just spilled her drink on herself.” From an internal, mental perspective we could respond,” Because she feels embarrassed.” Finally, from a biological perspective we could say, “Because her autonomic nervous system has signalled the blood vessels in her face to dilate.” Each explanation is correct, and each adds to our understanding of Jenna’s behavior. We might say that each explains Jenna’s behavior at a different level.

### Activity: Exploring Career Opportunities {-}

```{block2, type='reflect'}

The resources below are intended to provide you with opportunity to explore the “What do Psychologists do?” question more deeply. The first of the following resources will help you to make the most of your undergraduate time in psychology and clarify some of the postgraduate educational and vocational options available to you. The second site discusses some of the kinds of topics towards which psychologists focus their research and practice. The goal of resources like these is to help you determine which direction you may most enjoy in the field of psychology.

- Careers in Psychology [https://www.psywww.com/careers/index.html]{target="_blank”} 
- Canadian Psychological Association - Careers [https://cpa.ca/students/career/]{target="_blank”}
After exploring the different opportunities, consider the following questions:
- For what careers would a psychology major be helpful?(The internet has information on this.)
- What are the steps necessary to become a psychologist in private clinical practice?
- What’s the difference between a psychologist and a psychiatrist?
- Which perspective or level of explanation do you personally find the most interesting? Why?
- Why are some people wary of psychology?(A well-known televangelist once said, “You can’t be a Christian and a psychologist.”) What dangers do they see in studying psychology? Is there any justification for their fears?

*Be prepared to share your thoughts and insights with other members of the class*

```

## Thinking Critically with Psychological Science - Limits of Psychology

***Isn’t is just common sense?***

As a behavioral science, psychology fits the description of all science attributed to Einstein—“nothing more than the refinement of everyday knowledge.” Psychology often refines what we already know, or at least suspected. For example, everyday knowledge tells us, “Opposites attract.” Psychology will tell us some of the conditions under which this is true and when it is not. But everyday knowledge also says, “Never too old to learn,” and “You can’t teach an old dog new tricks.” So which is it? Through careful study of relevant conditions, psychology can help us decide.
(If you are interested in the folk wisdom of familiar sayings, and perhaps want to look for contradictory sayings, try Proverbs That Contradict Each Other)

Sometimes you may feel that psychologists’ discoveries are things you knew all along. In fact psychologists have studied this phenomenon too! They call it the hindsight bias. The hindsight bias is the feeling you get, after you learn something new, that you knew it all along (Hawkins & Hastie, 1990). However, I think that many of the things you will discover are somewhat surprising and unexpected, and you will enjoy this “refinement of everyday knowledge.”

***Isn’t it potentially dangerous?***

Like all knowledge, the value (or danger) of psychological knowledge is in how it is used. The following are potential misuses of psychological knowledge:

1. An understanding of some of the causes of behavior might lead to the inaccurate conclusion that all behavior could be explained and predicted if we had enough knowledge. We are robots, not free individuals.  
2. Psychological findings might be generalized beyond the situations in which they were found to be valid.  
3. Knowing some of the explanations for behavior takes away the mystery and wonder of human action.  
4. Understanding the causes of behavior can lead to the manipulation of people, perhaps even without their awareness.  
5. Psychological explanations leave no room for important religious beliefs.  

### Activity: Ethics in Psychology {-}

```{block2, type='reflect'}

What kind of ethical questions do you think might arise in the study of psychology? Should there be limits to the use of animals to learn about basic mental or physical processes? What limits and guidelines would you suggest?
What about research with humans? It is probably obvious that research should not inflict harm. But could even asking certain questions cause a certain amount of distress in some people? What about deception? Should it ever be used? If so, when and why? When does field research (the observation of people in natural settings) become an invasion of their privacy?

You can find a complete listing of ethical guidelines for research in psychology at:

- Canadian Psychology Association  
- American Psychology Association [https://www.apa.org/ethics/code/index]{target="_blank”}  

After reading about ethics in psychology, consider the following question:

- Do you think you would ever use deception in your research? If so, when would you use it?  

```

### Activity: Terminology Practice {-}

```{block2, type='reflect'}

Take a moment to self-assess how well you know some of the concepts introduced in this unit. While this activity is not formally graded, it can help support your understanding of the content.

<p>
    <iframe scrolling="yes" src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=95" allowfullscreen="allowfullscreen" width="100%" height="1000" frameborder="0" title="Unit 1 - Terminology Practice"></iframe>
</p>
<script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>


```

## Assessment {-}

```{block2, type='assessment'}

Refer to the course schedule for graded assignments you are responsible for submitting. **All graded assignments, and their due dates, can be found on the “Assessment” tab.**

In addition to any graded assignments you are responsible for submitting, be sure to complete all the Learning Activities that have been provided throughout the content - these are intended to support your understanding of the content.

```

## Checking your Learning {-}

Before you move on to the next unit, you may want to check to make sure that you are able to: 

```{block2, type='progress'}

- Define the key terminology of the scientific method.  
- Define important historical terminology from the field of psychology.  
- Describe the steps of the scientific method, the concept of scientific literacy, and how various philosophical and scientific fields became major influences on psychology.  
- Apply the biopsychosocial model to behaviour, the steps in critical thinking, and your knowledge to distinguish among the different specializations in psychology.  
- Analyze the use of the term scientific theory and how the philosophical ideas of empiricism and determinism are applied to human behaviour.  

```






















<!-- 
### Learning Activity: Chapter 2 Review Quiz {-}

```{block2, type='reflect'}

In order to review some of the major concepts from the text, take the following unmarked quiz. Although you will not be evaluated on these terms, they will assist you in the assignments for this course.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=78" width="648" height="969" frameborder="0" allowfullscreen="allowfullscreen" title="Psych 106 - Chapter 2 Review"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
  
```

## Thinking and Problem Solving

### Thinking {-}

“So God created man in his own image, in the image of God created he him; male and female created he them.” (Genesis 1:27)

“I will praise thee; for I am fearfully and wonderfully made.” (Psalm 139:14)

The human image of God means many things. It seems that one aspect of this image is our thinking ability, including our ability to solve problems and speak. How important is our thinking ability in our reflection of God’s image? What does your answer mean for people with less ability? What about people who lose abilities due to accident or disease (e.g., Alzheimer’s patients)?

### Algorithms & Heuristics {-}

Algorithms and heuristics can be confusing. An algorithm is a guaranteed route to a solution, but it may be the long way around to success. If you knew a person lived somewhere in a large residence hall, an algorithm for finding that individual would be to knock on every door until you located the person. Heuristics, on the other hand, sug­gest that you would first ask friends where to locate the person, or check a list, then knock on the appropriate door to locate the person. Another way to think of heuristics is the phrase "rule of thumb." Can you think of some rules of thumb that you have learned from your various job experiences? They may have to do with how long to cook a hamburger, or when to refill a machine, or how to get a date.

Consider the following example and explanation taken from Invitation to Social Psychology by Ron Philipchalk:

*In the second part of the book, they tell you how to crack a safe. There are all kinds of ninny-pinny, dopey things, like "It might be a good idea to try a date for the combination, because lots of people like to use dates." Or "Think of the psychology of the owner of the safe, and what he might use for the combination." And "The secretary is often worried that she might forget the combination of the safe, so she might write it down in one of the following places—along the edge of her desk drawer, on a list of names and addresses . . ." and so on . . . .*

*I also did a certain amount of systematic study. For instance, a typical combination was 69-32-21. How far off could a number be when you're opening the safe? If the number was 69, would 68 work? Would 67 work? On the particular locks we had, the answer was yes for both, but 66 wouldn't work. You could be off by two in either direction. That meant you only had to try one out of five numbers, so you could try zero, five, ten, fifteen, and so on. With twenty such numbers on a wheel of 100, that was 8000 possibilities instead of the 1,000,000 you would get if you had to try every single number. . . .*

*I practiced all the time on my own safe so I could do this process as fast as I could and not get lost in my mind as to which number I was pushing and mess up the first number. Like a guy who practices sleight of hand, I got it down to an absolute rhythm so I could try the 400 possible back numbers in less than half an hour. That meant I could open a safe in a maximum of eight hours—with an average time of four hours. (Surely You're Joking Mr. Feynman, p. 140)*

Mr. Feynman's safecracking system succeeds because he methodically works through every possible combination. By logical analysis he has discovered which 8,000 possibilities out of 1,000,000 he needs to try. We call this type of logical step-by-step procedure for solving problems an algorithm (Newell & Simon, 1972; Simon, 1981). If you use the correct algorithm your success is guaranteed.

But sometimes it can take a long time to discover the correct algorithm. And employing an algorithm is often time consuming. Mr. Feynman spent days developing his system and it took hours to open a safe. You could certainly open a safe much faster if you found the combination on the edge of the secretary's drawer.

The shortcuts Mr. Feynman calls "ninny-pinny, dopey things" are examples of heuristics. Heuristics are rule-of-thumb strategies for solving problems, shortcuts we develop from our experience. Heuristics often help us eliminate improbable alternatives and guide us to the most likely solution to a problem. Despite his appreciation for algorithms, Mr. Feynman discovered heuristics can be useful. He found, for example, that safe owners often did not bother to change the factory set combination when they received a new safe. In one office building the temporary factory combinations 25-0-25 or 50-25-50 opened one safe in five

Algorithms and heuristics are examples of cognitive strategies—mental plans we use to make decisions and solve problems.


### Activity: Read and Reflect {-}

```{block2, type='reflect'}

- Read Chapter 8 from your text and review the notes.

```

### Activity: Problem Solving Activities {-}

```{block2, type='reflect'}

In this lesson, we spent time exploring cognitive strategies used to solve problems and make decisions. We now have an opportunity to practice this on our own Take a look at the following problems and see if you can find a solution. As you work through the problems, think about what cognitive strategies you are implementing as you make each decision:

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=573" width="760" height="383" frameborder="0" allowfullscreen="allowfullscreen" title="Unit 1 - Problem Solving Activity"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

<span class="blockhead">Problem Solving Practice</span>

Below is a website that provides more opportunity to work through, and solve, some problems. Specifically, this resource explores the idea of ***Assumptions*** and the role assumptions play when solving problems. Furthermore, this is a valuable resource as it also explores other important techniques to be implemented when solving problems.

Click on the following link and read through the information as you continue to practice your problem solving:

- [**Virtual Salt**](https://www.virtualsalt.com/problem-solving-techniques/){target="_blank”}

```

### Activity: Questions for Consideration {-}

```{block2, type='reflect'}

Read the following and consider the questions below:
In the largest sense, society is breaking into two classes:
  
*The first class are people who know how to think. These people realize that most problems are open to examination and creative solution. If a problem appears in the lives of these people, their intellectual training will quickly lead them to a solution or an alternative statement of the problem. These people are the source of the most important product in today's economy-ideas.*

*The second class, the vast majority of society, are people who cannot think for themselves. I call these people ‘idea consumers’ – metaphorically speaking, they wander around in a gigantic open-air mall of facts and ideas. The content of their experience is provided by television, the Internet and other shallow data pools. These people believe collecting images and facts makes them educated and competent, and all their experiences reinforce this belief. The central, organizing principle of this class is that ideas come from somewhere else, from magical persons, geniuses, ‘them.’*

- ***Do you agree or disagree with this claim?***
- ***Do you know people that fit in the second category? What causes this difference? How might it be changed?***

*Be prepared to share your thoughts and insights with other members of the class*

```

## Cognitive Biases

As if the biases mentioned in the textbook are not enough, here are a few more to watch out for, taken from Invitation to Social Psychology by Ron Philipchalk.

### The Gambler's Fallacy {-}

Jill and Bob are the parents of three boys. Jill is pregnant again, and she and Bob are hoping the baby is a girl. In fact, they are confident the baby must be a girl because their previous three children were boys. If you agree with Jill and Bob that the baby is more likely to be a girl than a boy, then you—along with Jill and Bob—may be committing the gambler's fallacy. No matter how many boys have been born, the likelihood of a girl being born is the same as it always was, approximately 50 % (assuming no biological abnormality or medical intervention).

The gambler's fallacy arises from our failure to recognize the independence of unconnected events. The result of a coin toss does not depend on the outcome of previous tosses; a child's sex at conception is not affected by the sex of prior conceptions; the cards dealt in a hand are not influenced by the distribution of cards on the previous deal; and so on. Each event in these sequences is independent of the others, although we tend to think that somehow there must be a connection.

### The Anchoring and Adjustment Heuristic {-}

First impressions of a person exert a powerful influence on the way we interpret subsequent information about that person. This effect may be an example of a more general principle called the anchoring and adjustment heuristic. Information we use to establish a starting value (or anchor point) tends to be more influential in our decisions than subsequent information we use to adjust this value (Tversky & Kahneman, 1974).

Daniel Cervone and his colleagues found, for example, that initial success or failure on a task can establish an anchor for feelings of self-efficacy. Students who initially succeed on a task and later fail have higher feelings of self-efficacy than students who initially fail and later succeed even though their overall level of success is the same. Final judgments of self-efficacy are biased in the direction of initial judgments (Cervone & Palmer, 1990; Peake & Cervone, 1989).

Salespeople often use the anchoring and adjustment heuristic to their advantage. Some real estate agents routinely show their clients an over-priced and unattractive house first in order to set an anchor point which, in effect, says, "The kind of house you want is going to cost a lot." Once established, this expectation of high price changes very slowly and the clients are relieved to find an acceptable house in their price range (Northcraft & Neale, 1987).

Car dealers too like us to set our sights high. Their so-called list price establishes an anchor or reference point that overshadows our subsequent evaluations, as I recently discovered. In looking for a certain model of car, I was attracted to a particular vehicle with an asking price of $3,800 ("reduced from $4,200"). I believed this price was too high, so I bargained with the vendor. Eventually, I bought the car for $2,800. Did the high original asking price affect my decision? Yes, it probably did. Subsequent events indicated I still paid too much. I later bought an identical model in only slightly poorer condition for $2,000. I was a victim of the anchoring and adjustment heuristic.

***Contrast Effects***

My car purchase also illustrates a related distortion in judgment, the contrast effect. In contrast to the original price of $4,200 my offer of $2,800 seemed like a bargain. John Lynch, Jr. and his colleagues (1991) found a similar effect with students. The students rated low-priced cars as less expensive when they were considered alongside high-priced cars (contrast effect), compared to when they were considered along with other low-priced cars (no contrast).

Research by Douglass Kenrick and his colleagues indicates that we also show contrast effects in evaluating other people. In one study (1980), male college students rated the attractiveness of potential blind dates. Subjects who gave their ratings after watching a TV show with attractive female actresses rated the potential dates as less attractive than did subjects who rated their potential dates before watching the show. In another study (1989), after viewing centerfold erotica, men found average women—and even their own wives—less attractive.

### Heuristics & Biases {-}

By now you may be wondering why we fall prey to so many cognitive biases and errors. Well don’t worry; our biases are actually a side effect of our cognitive efficiency. Most of our biases result from using heuristics, rules of thumb, or mental shortcuts that work very well. Sometimes they let us down, but overall, they improve the speed with which we handle mental problems—much like Mr. Feynman’s safe-cracking tricks. As we noted in the previous discussion, you could certainly open a safe much faster if you found the combination on the edge of the secretary's drawer. However, you won’t always find the combination there, so limiting yourself to this approach would produce a kind of “cognitive bias” in your safe-cracking strategy.


```{block2, type='caution'}

**Online Articles of Interest** 
  
For additional information and examples, click on the link below:

- [**Cognitive Biases**](https://en.wikipedia.org/wiki/List_of_cognitive_biases){target="_blank”}

```


### Activity: Questions for Consideration {-}

```{block2, type='reflect'}

Consider what you have learned in this section - take a moment to reflect on the following:

- ***Can you think of an example from your own experience of one of the cognitive biases, discussed here or in the textbook, that you have fallen prey to.***
  
*Be prepared to share your thoughts and insights with other members of the class*
  
```

## Language and Thought

### Linguistic Relativity {-}

Benjamin Whorf’s linguistic relativity hypothesis suggests that our language affects the way we see the world. Do you know any examples of weather terms, for example, that are unique to one area? Could knowing these terms help you to notice differences in weather that outsiders might not notice? What about in sports? Sports fans usually know terms to de­scribe certain strokes or plays. Does knowledge of these terms affect percep­tion? Can you think of some examples? What does it mean to “clothesline” someone, or “post-up,” or “birdie?”

### Imaginary Practice {-}

Mental practice is now widely accepted in many areas. The following excerpt is taken from the [**GolfPsych**](https://www.golfpsych.com){target="_blank”} website. You may find further examples there as well.

"You can practice the mental aspects of your game anytime. We encourage our clients to do imagery practice of playing well in upcoming tournaments. This imaginary practice includes seeing the course, situation, doing a full mental pre-shot routine and seeing a good shot. You should also be feeling the way you do when you play your best. In addition, you should be practicing deep breathing and quieting your mind off-course. This is an extremely valuable tool that must be practiced to be effective. The mental game is much more than thinking positive thoughts. Take our Personality Assessment and get your own GolfPsych Report to receive our recommendations for you based on your personality and our research. Reading our book will also help you understand all aspects of a good mental game. During your practices and before your rounds you should also be practicing your mental skills."



### Activity: Introduction to Visualization {-}

```{block2, type='reflect'}

In this Topic, we learned about the notion of mental practice. Below is an article that will take you through the process of visualization. Take some time to read the article and practice for yourself. Pay careful attention to your thoughts, your focus, your feelings as you engage in the process.

- [**Introduction to Visualization**](https://www.forbes.com/sites/bhaligill/2017/06/22/new-to-visualization-here-are-5-steps-to-get-you-started/#60dafcdc6e3f){target="_blank”}
                                        
```

### Activity: Question for Consideration {-}

```{block2, type='reflect'}

The subject of our focus for this section has been on the power of language in influencing how we see the world. In this activity, you are asked to focus on the importance of language in the Bible (and other religious writings) and how it "shapes" how we see the world.

Carefully consider the following question:

- ***Give some examples of the importance of language in the Bible or other religious writings.***

*Be prepared to share your thoughts and insights with other members of the class*
  
```

## Animal Language

### Language {-}

As a Christian I am pleased to see in psychology the resurgence of interest in studying some of what Ronald Koteskey (1980) calls humanity's "God-like" characteristics, creativity, imagery, and particularly language.

The use of words is extremely important in Christian scripture. God spoke the creation into existence; Jesus is called the Word; the significance of Babel and Pentecost are closely linked to the importance of language; and there is great power associated with an individual's name. In addition, Christians have usually considered the ability to communicate with words to be part of the image of God in man. However, recently several researchers claim to have taught animals, usually chimpanzees or apes, to communicate through language. Using sign language, blocks, or keyboards and computer- generated voices, the animals have signaled their needs and even generated word combinations.

But is this truly language? There is no doubt that the animals are using symbols as signs to stand for objects and actions. However, there are significant questions being raised about the comparison with human language.

Christians need to think carefully about what they mean when they talk about the image of God in man. The area of human learning and psycholinguistics offers some intriguing questions for thoughtful Christians. What is the origin of human speech-is it learned (as Skinner would say) or largely innate (as Chomsky would say)? Is human speech unique? Do the studies of language in animals necessitate a redefinition of the uniqueness of man? (Based on Psychology and Christianity by Ron Philipchalk, p. 102)

```{block2, type='caution'}

**Online Articles of Interest**  

To add to our exploration of this topic, take a moment to read the following articles:

- [**Chimp Talk Debate: Is It Really Language?**](http://tuvalu.santafe.edu/~johnson/articles.chimp.html){target="_blank”}  

- [**Animal Language and Cognition Projects**](https://www.massey.ac.nz/~alock/hbook/ristau.htm){target="_blank”}  

```

### Activity: Questions for Consideration {-}

```{block2, type='reflect'}

Take a moment to consider the following questions:

- ***How important for our understanding of who we are as humans is the distinctiveness of our language ability? Is it a sign of the image of God?***

*Be prepared to share your thoughts and insights with other members of the class*
  
```

## Assessment {-}

```{block2, type='assessment'}

Refer to the course schedule for graded assignments you are responsible for submitting. **All graded assignments, and their due dates, can be found on the "Assessment" tab.**
  
In addition to any graded assignments you are responsible for submitting, be sure to complete all the Learning Activities that have been provided throughout the content - these are intended to support your understanding of the content.


```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Define key terminology related to principles of scientific research, research designs, and statistics.  
- Explain the five characteristics of quality scientific research, and the pros and cons of descriptive, correlational, and experimental research designs.  
- Determine how biases might influence the outcome of a study and how experiments help demonstrate cause-and-effect relationships.  
- Apply the concepts of reliability and validity to examples and concepts of experimental methods to research examples.  
- Assess whether anecdotes, authority figures, and common sense are reliably truthful sources of information.  
- Understand what it means for variables to be positively or negatively correlated and how and why psychologists use significance tests.  

```

Hidden comment -->