# The Developing Person - Part 2

## Overview {-}

Building upon Unit 3, this unit (Part 2) will focus on the cognitive, physical, and social changes faced during young (and emerging) adulthood, middle adulthood, and late adulthood. *Please note as well, that although it is not covered in the text, Topic 2 discusses the important, and inevitable, subject of dying and death.*

### Topics {-}

This unit is divided into the following topics:

1. Adulthood  
2. Death and Dying  

### Learning Outcomes {-}

By the end of this unit, student's will be able to:

- Define the key terminology concerning adulthood and aging.  
- Describe the key areas of growth experiences by emerging adults.
- Explain age-related disorders such as Alzheimer’s disease.  
- Describe how cognitive abilities change with age.  
- Apply effective communication principles to the challenge of improving your own relationships.  
- Analyze the stereotype that old age is a time of unhappiness.  

### Activity Checklist: {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

```{block2, type='reflect'}
<span class="blockhead">Learning Activities</span>

- Read the relevant sections of Chapter 10 of your textbook
- Review Unit 4 Slides (intended to support your understanding of your readings) - *scroll to bottom of page*
- Read about *Erikson’s Eight Psychosocial Stages* that highlight the importance of relationships in healthy aging.
- Read and Reflect: Explore the resources that focus on again and dying and consider how these concepts affect individuals.
```
```{block2, type='caution'}
***Note***  
The course units follow topics in the textbook, *Revel for An Introduction to Psychological Science* by Krause et al. (4th Edition). For each unit, please read the pertinent chapter(s) before completing the assessment for the unit.
```

```{block2, type='assessment'}
***Assessment***  
In this course you demonstrate your understanding of the course learning outcomes in different ways, including papers, projects, discussions and quizzes. Please see the Assessment section in Moodle for assignment details and due dates.
```

### Resources {-}

Here are the resources you will need to complete this unit:

- Krause, M., Corts, D., & Smith, S. C. (2024). *Revel for An Introduction to Psychological Science, 4th Canadian Edition.* Pearson Ed. 
- Other resources will be provided online.  

## Adulthood

### Psychosocial Development {-}

There are many changes we experience during the time we call adulthood. According to Erikson's theory of psychosocial development, adults move through three important stages during which they must resolve important psychosocial conflicts:

- Early Adulthood  
- Middle Adulthood  
- Late Adulthood  

***In Early Adulthood*** (20-40 years of age) the psychosocial crisis is one of intimacy versus isolation. Although it is often perceived as critical whether or not the person develops an intimate relationship with a lifelong partner, Erikson believed that although this is one component of intimacy in this stage, other types of intimacy are also important—like developing intimate relationships with workmates, colleagues, and even one’s children. If one fails to develop a sense of intimacy during this stage, he or she will feel isolation.

***In Middle Adulthood*** (40-65 years of age) the psychosocial crises is one of generativity versus stagnation. What is generativity? Erikson used the term gererativity to describe the process by which a person feels like he or she is making a lasting contribution in the world. Usually, generativity involves giving something back to the next generation. People at this stage can feel generative in many ways—coaching a softball team, being a scout leader, teaching children in Sunday School, been a big brother/sister, etc. If a person fails to develop a sense of generativity during this stage, he or she will feel a sense of stagnation.

***In Late Adulthood*** (65+ years of age) the psychosocial crisis is one of ego integrity versus despair. If the individual looks back on his or her life and feels a sense of pride in the accomplishments he or she has made, then the individual will feel a sense of ego integrity. However, if the person looks back on his or her life and does not see the significance of his or her accomplishments, then he or she will feel a sense of despair at the meaninglessness of his or her life.

### Guilt {-}

One of the most significant developments in childhood, from both a secular and Christian point of view, is a conscience with its attendant guilt. Is guilt simply a conditioned emotional response (as the behaviorist might say)? Is it the result of conflict with the superego (as a psychoanalyst would say)? Is it the failure to live up to our self-concept (as the humanist might say)? Is it the voice of the Holy Spirit? Or is it some combination of these? (For help on this issue and an important distinction between false and true guilt see Counts and Narramore (1970), Narramore (1984), Tournier (1962).) *(from Psychology and Christianity, by Ronald Philipchalk, p. 146)*

The textbook discusses moral development in childhood and adolescence. However, many adults are troubled by questions of right and wrong, and in particular, by feelings of guilt. The Christian authors noted above suggest that many guilt feelings are not true guilt but false guilt carried over from childhood experiences. Understanding how conscience and guilt feelings develop can help to liberate us from unnecessary false guilt inappropriately attributed to God.

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

This activity involves some reading and reflection around Erikson’s Eight Psychosocial Stages and an article from Harvard University illuminating the importance of relationships in healthy aging.

- [**Erik Erikson’s Stages of Social-Emotional Development**](https://childdevelopmentinfo.com/child-development/erickson/#gs.d8mpcv){target="_blank”}  
- [**Good Genes are Nice, but Joy is Better**](https://news.harvard.edu/gazette/story/2017/04/over-nearly-80-years-harvard-study-has-been-showing-how-to-live-a-healthy-and-happy-life/){target="_blank"}  

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***What do you hope to accomplish during your “adult development” years?***  
  - *(If you are past these years, what are you most pleased with?)*  

## Death and Dying

### Death {-}

Secular psychologists see death as final. Christians, however, see resurrection beyond, with death being but another step in that direction. What implications do these beliefs have for the process of dying?

As medical technology has advanced death has become more and more difficult to define. We need to focus our attention less on preserving the physical and more on preserving the personhood of the individual. This means giving greater attention to our concept of the dying person created in the image of God (as the abortion issue has forced us to do at the other end of life). When is personhood sacrificed to technical efficiency? Should we advocate a more "natural death?" What is "natural death?" How far does one go in "allowing" natural death? *(from Psychology and Christianity, by Ronald Philipchalk, p. 146)*

### Hospice {-}

You matter because of who you are. You matter to the last moment of your life, and we will do all we can not only to help you die peacefully, but also to live until you die.” *(Dame Cicely Saunders)*

During the Crusades of the Middle Ages a hospice provided lodging for travelers: a place of refuge and comfort. So in 1967, when Dame Cicley Saunders opened a facility in London to provide care and comfort to dying people and their families, St. Christopher’s hospice was an appropriate name. *(Courtesy of the Langley Hospice Society)*

*If you would like to know more about the hospice movement in this area, you can contact the Langley Hospice Society at 604-530-1115.*

### Cultural Variations {-}

The following issues are often subject to cul­tural variations:

- Adolescence is unknown in some cultures  
- Adolescent struggles and conflict are much less in some cultures (e.g., )  
- Stage theories may not apply in other cultures  
- Ageism, especially with regard to intellectual abilities, is reduced, unknown, or even reversed in some cultures where the wisdom of old age is venerated  
- The "social clock" may be set differently in other cultures  
- Attitudes toward death vary greatly between cultures  

<!-- [plugin:content-inject](_activities) -->

## Assessment

```{block2, type='assessment'}

In addition to your participation in this unit's Learning Lab, you will also be responsible for two formal assessments. The first, is your **Writing Assignment #1** - more information can be found on this assignment by scrolling down the page. The second assessment that will take place is **Quiz #1** - more information can be found by scrolling down the page.

*Active participation in group exercises, reflection, and critical discourse is an essential component of this course. You are expected to show respect for all members of the course, both in your speech and actions. Contribute by actively observing and listening, raising thoughtful questions, examining relevant issues, building on others’ ideas, analyzing and evaluating the group’s thinking, synthesizing key points, and expanding the group’s perspectives. Take care not to dominate a conversation, giving space for others to speak. When in small groups help maintain the focus, flow, and quality of conversations, and take the initiative to invite others (particularly those who are quiet) to speak.*

**Rubric for Participation in Learning Labs**

| Emerging (0-64%) | Developing (65-89%) | Mastering (90-100%)|
| -| -|-|
|Never to almost never: Demonstrates active listening (as indicated by disengaged body language and no to rare comments that build on others’ remarks),Initiates any contributions in class or small groups, Makes insightful or constructive comments, Helps maintain a supportive space for others to speak.|Sometimes to fairly often: Demonstrates active listening (as indicated by somewhat to often engaged body language and comments that build on others’ remarks), Initiates a contribution at least once in a class or small group discussion; Makes insightful or constructive comments, Helps maintain a supportive space for others to speak.|Very often to nearly always: Demonstrates active listening (as indicated by fully engaged body language and comments that build on others’ remarks), Initiates more than one contribution in a class or small group discussion, Makes insightful or constructive comments, Creates a space for others to speak and takes initiative to include others.

<span class="blockhead">Writing Assignment #1</span>

Your first assignment for the course will involve reading a formal research article and extracting important information. Research articles play an important role in psychology as they present new findings and research that help us better understand the subject field. It is, however, important for us to understand what information is important as we weigh the value of the article we are reading. This assignment attempts to help us better understand those considerations.

Your first task is to read [**How to Read Empirical Articles**](assets/unit_4/Assessment_Empirical_Short.pdf)

As you can see, it is important to understand ***why*** you are reading an article and it is important to understand ***what*** you want to get out of it.

Next, your task is to read [**How to Read a Journal Article in Social Psychology**](assets/unit_4/Assessment_Empirical_Long.pdf)

- This article should help support your understanding of formal research articles and how to read them to support your research and learning.  

<span class="blockhead">Writing Assignment</span>

Finally, it is time to apply what we have learned. Download the following article:

[**No More FOMO**](assets/unit_4/Assessment_FOMO_Article.pdf)  

<!-- [plugin:content-inject](_alert)  -->

After reading the article above, use the content to respond to the following questions:

1. **Does this study reflect basic or applied research? How do you know?**  
2. **What level(s) of analysis (biological, psychological, environmental) are being employed in this study? Explain and identify the specific details of the study that show this.**  
3. **What were the findings of previous research that led the researchers to do this study? What was the research question that they attempted to answer? What was (were) the researchers’ hypothesis(es)?**  
4. **How was this study conducted? Was it an experiment or a non-experiment? How can you tell? What were the variables under investigation in this study? Identify the dependent and independent variables, if applicable.**  
5. **What were the main findings of this study? How do they relate to the original study hypothesis(es)?**  
6. **How do the researchers explain their results? What are some other possible explanations? What are some strengths of this study? Limitations?**  
7. **What are the possible implications of these results in the real world?**  

<span class="blockhead">Rubric for Writing Assignment #1</span>

**In addition to the criteria included in the rubric below, it is expected that students submit their assignments with an APA style title page.**

Estimate that each response will be between one paragraph to ½ a page (depending on what the question is asking and how much information is in the article). The total amount of content will be between 2 ½ to 3 pages (not including the title page).

| **Exceeds Expectations** | **Meets Expectations**          | **Minimally Meets Expectations**           | **Does Not Meet Expectations**                 |
||--|--|-|
Responses are accurate and address the questions in a comprehensive manner|Responses are accurate  and address the questions but could demonstrate more meaningful comprehension  of content|Responses may lack accuracy in addressing the questions and/or may demonstrate limited comprehension of content|Responses do not  accurately address the questions or do not demonstrate any comprehension of content|
Clear, precise and well-reasoned responses| Mostly clear, precise and well-reasoned responses |Some clear, precise and well-reasoned responses | Responses lack clarity, logic and/or precision|
|Spelling and grammar are accurate.| Minor and/or few spelling or grammatical errors.| Several spelling or grammatical errors.|

***To submit your completed assignment, scroll to the bottom of the page and click on the "Writing Assignment #1" tab - follow the directions there.***

<span class="blockhead">Quiz #1</span>

Upon completing your first Writing Assignment, you will next complete your first quiz.

Your instructor will provide additional instructions. Student's will be provided with one attempt. You will be provided information about when the quiz will open so you can begin.

***To begin your quiz,*** click on the **Quiz #1** tab at the bottom of the screen.

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Define the key terminology concerning adulthood and aging.  

- Describe the key areas of growth experiences by emerging adults.  

- Explain age-related disorders such as Alzheimer’s disease.  

- Describe how cognitive abilities change with age.  

- Apply effective communication principles to the challenge of improving your own relationships.  

- Analyze the stereotype that old age is a time of unhappiness.  

```
