# Social Psychology - Part 2

## Overview {-}

In this unit, we continue to build upon Unit 6. No single factor has more impact on shaping the quality and direction of your life over virtually every aspect of your existence than relationships. In a way, everyone is a social psychologist. People constantly form ideas/opinions about why a person or a group of people are acting the way they are. Social psychology is similar to what people find themselves naturally doing except it uses scientific tools to study these hypotheses (the ideas/opinions). Social psychologist are primarily interested in examining the different ways that individual’s effect groups of people and the way groups of people effect individual’s. In this unit you will be introduced to some historical studies and main concepts in this field. Topics covered in this chapter include social influences on behaviour, social impressions and judgements, the relationship between attitudes and behaviour, and effective communication. In Unit 6 (Part 1) you looked at attributes and actions, conformity, obedience, and compliance.

Please note that this unit will also examine prejudice and aggression. Although these topics are not specifically covered in the textbook, they are important to social psychology, attraction, and altruism.

### Topics {-}

This unit is divided into the following topics:

1. Prejudice and Aggression  
2. Attraction and Altruism  

### Learning Outcomes {-}

By the end of this unit, student's will be able to:

- Define the key terminology associated with social influence, social cognition, and on attitudes, behaviour, and effective communication.  
- Describe why individuals conform to others’ behaviours, how individuals and groups can influence behaviours, and how we form first impressions and how these impressions influence us.  
- Apply your knowledge of the bystander effect to ensure that you will be helped if you are in an emergency, of social cognition to help overcome prejudice and discrimination, and of the central route to describe how a message should be designed.  
- Analyze whether guards who participate in abuse are inherently bad people, or if their behaviour is the product of social influences and whether people who commit discriminatory acts are necessarily prejudiced.  
- Describe how behaviours influence attitudes in terms of cognitive dissonance theory.  

### Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work:

```{block2, type='reflect'}

<!-- [plugin:content-inject](_schedule) -->


<span class="blockhead">Read and Reflect</span>

- Read *Krause et al. (2021). Revel for An Introduction to Psychological Science, 3rd Canadian Edition*  
- Review [*Unit 7 - Slides*](PSYC106-CH13SocialPsychology-3rdEd.pptx)  
//todo #5
- These will be the same slides from Unit 6 as both unit's cover Chapter 13 content.  

*Please note, the slides are intended to supplement the information found in your textbook. If you are having trouble viewing them, they can also be downloaded by scrolling to the bottom of the screen and clicking on the "Unit 7 - Slides" link.*  

- This activity is an opportunity to reflect on what you have been taught about racism and discrimination and attitudes of hate and violence. You will be able to ponder the ways in which your parent(s)/primary caregiver(s) addressed these topics as you were growing up in light of some current parental directions and encouragements regarding these topics. You’ll also be familiarized with some research considerations around the topic of video game violence and TV violence and their direct effects on anti-social attitudes and behaviours.

- In this activity you can gain more insight into what is it that potentially makes you attractive to someone else and you attractive to others. One of the components influencing this is the structure of a person’s face. Much research has been done on this and the first article will outline some of the ways your face has shaped your social experiences. The second article adds to this discussion by looking at how willing people are to acknowledge the role of attractiveness in their own thought processes and decision-making. Next, the topic shifts to altruism. The first of these articles proposes that only reciprocal altruism exists. I would encourage you to read this article through the lens of, “Is it truly possible to know another’s motivation or intention?” Lastly, Random Acts of Kindness is a website that offers great resources and opportunities to increase kindness in your, and others, lives.

<span class="blockhead">Key Terms Quiz</span>

**NOTE:** *Units 6 & 7 both covered content from Chapter 13 in your textbook - this quiz will also cover terms from both units.*

- Practice quiz to assess how well you know key terms from Chapter 13.  
 - Not for formal evaluation.  

<span class="blockhead">Learning Lab Preparation</span>

- Each topic will provide a question or scenario for you to consider prior to attending your Learning Lab. Be sure to carefully consider each prompt as you will be expected to contribute to the group discussion.  

```

### Resources {-}

Here are the resources you will need to complete this unit:

- Krause, M., Corts, D., Smith, S. C., & Dolderman, D. (2018). *Revel for An Introduction to Psychological Science, 2nd Canadian Edition.* Pearson Ed.  
- Other resources will be provided online.  

## Prejudice and Aggression

### Prejudice & Religion {-}

Some of the first research to study the effects of religion (Christianity) investigated its role in prejudice. The consistent finding of this line of study was that the more religious people were, the more prejudiced they were likely to be Allport and Kramer (1946). Because racial prejudice is so clearly contrary to religious teaching, Gordon Allport called this Religion's Grand Paradox. In the area of racial prejudice in North America, Christianity did not appear to improve behavior.

Religion's Grand Paradox was gradually resolved as researchers refined their definition of religious. When the apparently prejudiced church attenders were divided into those for whom religion served a social function and was a means to an end (extrinsic religious orientation) and those for whom religion was an integral part of their lives and an end in itself (intrinsic religious orientation), it was the extrinsics who had raised the prejudice scores of the entire group. The intrinsics were found to be even less prejudiced than the non-attenders. Apparently an intrinsic religious orientation has a beneficial effect on behavior, at least on racial prejudice (Allport, 1959).

### Sports as Catharsis? {-}

The idea that relieving emotional tension causes a purging of pent-up energy is called the catharsis hypothesis. According to Aristotle—who first proposed the concept of catharsis—even viewing powerful emotional events can be cathartic. Thus we should be able to reduce our aggressive tendencies by watching others act out their aggression, as well as by acting aggressively ourselves.

Research, however, does not lend much support to this common-sense idea. For example, Robert Arms and his associates report that hockey, football, and wrestling fans exhibit more aggression after viewing the event than before (Arms et al., 1979; Goldstein & Arms, 1971; Russell, 1983) (see Figure 11.1). Arthur Patterson (1974) found that high school football players were more aggressive after the season than before it. And Dane Archer and Rosemary Gartner report that a nation's murder rate tends to jump after a war is over (Archer & Gartner, 1976).

### Compensatory Machoism {-}

Marshall Segall and his colleagues point out that cultures typically expect men to be macho —that is, to behave in ways that indicate their strength, virility, and willingness to confront an adversary. But Segall and his colleagues suggest that biological mechanisms interact with complex cultural processes to produce a kind of "compensatory machoism." Very briefly, the elements in this process are these:

1. All societies have some division of labor by sex, resulting in sex-linked roles. For example, females do most of the child rearing in most societies and virtually all of it in some. Boys have less opportunity than girls to learn their roles by modeling because they are raised by women and have comparatively little contact with adult males.  
2. For various historical and environmental reasons, fathers in some societies are more likely to be absent. Paradoxically, in these societies young males are expected to develop a particularly distinct male identity. These young males are driven—consciously or unconsciously—to display "manly" behavior and avoid appearing "womanly" at all costs.  
3. Some societies recognize this need and provide initiation ceremonies that serve to "stamp in" masculinity for boys who need it because of inadequate opportunity to acquire it in childhood. These ceremonies affirm the young male's adult masculinity.  
4. Adolescent males in societies without initiation ceremonies may exaggerate their biological tendencies toward aggression in an attempt to assert their own masculinity.  

Segall and his associates explain, "We suggest that in societies that have the preconditions requiring a stamping-in of masculinity, but which don't achieve this through initiation ceremonies or other institutionalized practices, adolescent males will try on their own to assert their masculinity" (p. 281). The Segall group calls the resultant aggression compensatory machoism. Compensatory machoism is the display of behavior intended to identify oneself with the cultural image of masculinity. The resulting aggression is rooted not in anger but in a "felt need to escape from womanliness and to mark one's masculine gender" (p. 281).

***Can you think of a cultural group in North America that seems to illustrate this process particularly well?***

Marshall Segall and his colleagues suggest that many young black American males illustrate this process. Social conditions (unemployment, educational deficits, racial discrimination) contribute to a prevalence of broken homes with female-headed households. Young men in these conditions attempt to assert their masculine identity through compensatory machoism. They are tough, independent, and violently aggressive. As a result, murder is their leading cause of death. A black man in stands a 1-in-21 chance of being murdered in his lifetime, compared with 1 in 131 for white men and 1 in 369 for white women. The Segall group quotes one young black male who says that in urban ghettos *"You must walk angry, talk angry, think angry . . . . You're either a chump or a champ . . . . You're macho or gay." (adapted from Invitation to Social Psychology by Ronald Philipchalk)*

### Empathy & Aggression {-}

Several researchers suggest that empathy and concern for others may be important tools for reducing aggression. Prejudice, discrimination, and violent sexual aggression flourish when we dehumanize a victim. If a policeman is a “pig,” a homosexual a “fag,” or a woman a “playmate,” “pet,” or “bitch,” it is easier to excuse and even justify our hostile actions. Empathy reverses this process by making us identify with a potential victim. For example, Ken-Ichi Ohbuchi and his colleagues found that Japanese students gave less shock to a "victim" if the victim first aroused subjects' empathy by disclosing information about herself or by expressing her fear of shock. *(adapted from Invitation to Social Psychology by Ronald Philipchalk)*

### Conflict Resolution & Culture {-}

Fumie Kumagai and Murray Straus report significant differences in the way con­flicts are resolved between marital partners in different cultures. Using the "Conflict Tactics Scale," these researchers asked high school seniors in, and the United States how their parents settled disputes. Violent means of "resolution" were most common in American couples, followed by Japanese, and then Indian couples.

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

The following articles are intended to deepen your understanding of discrimination, racism, hate and violence. Hopefully this information will cause you to consider how you’ve been informed about these topics. Additionally, it may be valuable, in light of the research, to consider how much hate and violence you have exposure to through gaming and TV and how this is impacting your attitude and behaviour towards other people. Click on the articles below:

- [**Discussing Hate and Violence with Children**](https://www.adl.org/education/resources/tools-and-strategies/discussing-hate-and-violence-with-children){target="_blank”}  
- [**Resolution on Violent Video Games**](https://www.apa.org/about/policy/violent-video-games){target="_blank”}  
- [**Television and Video Violence**](https://www.apa.org/action/resources/research-in-action/protect){target="_blank”}  

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***If removing parts of the brain reliably reduced aggression, do you think violent criminals should be forced to have this operation?***
- ***Should violent content be removed from video games, movies, and TV (why or why not)?***

```

## Attraction & Altruism

*Why do I like you? Let me count the ways:*

- We often like people for whom we have suffered.  
- We like people more after we have done small favours for them.  
- We like people best whose (accidentally over­heard) descriptions of us begin on a negative note and end with a posi­tive tone.  
- We like people who convert to our point of view better than we like people who have agreed with us all along.  
- We like highly competent people better after they have committed a blunder.  

### Culture & Attraction {-}

The characteristics that are attractive in the opposite sex, as well as the impor­tance of physical attractiveness, are different in different cultures. Deborah Stiles and her colleagues found that Mexican adolescents valued liking children, helping others, high intelligence, and inner goodness and honesty in their oppo­site-sex ideal. American adolescents gave higher ratings to having a lot of money, being fun, popular, good looking, and sexy. Karen Dion and her colleagues found that physical attractiveness is more impor­tant in a culture where individualism (Canadian) rather than collectivism (Chinese) is valued.

David Buss and 49 collaborators in 33 countries asked young men and women (average age 23 years) about the attributes they looked for in potential mates. The researchers found many differences among cultures. The most pervasive difference they found was the emphasis given to "traditional" versus "modern" attributes. Young people looking for a mate in, and place great value on the traditional attributes of chastity, home and children, domestic skills, and providing for the family. At the other extreme, in the , , , and , young people looking for mates did not consider these attributes very important.

***(Canadian and American values were in between these extremes).***

American young people differed from the international average by placing a higher value on a college degree, earning capacity, heredity, and "an exciting personality." They placed a relatively low value on housekeeping skills, and intelligence (Buss, 1990). Without this kind of information it would be easy for us to assume that people in other cultures look for the same qualities in their potential mates as we do. *(adapted from Understanding Human Behavior by Ronald Philipchalk)*

### Culture & Altruism {-}

Ronald Johnson and George Danko (1989) report significant differences in altru­ism between cultures in , , , , the , and . Benjamin Colby reports that differences in altruism between stu­dents from 133 different cultures were predictive of their ability to adapt to university culture (altruistic students adapted better). In one study Wegner and Crano found that racial fac­tors affected helping behavior. An exper­i­menter who was apparently engrossed in examining a deck of 500 computer cards approached naive subjects. Approximately one step away from the subject, the experimenter "accidentally" dropped the entire deck. Blacks helped whites 17 percent of the time but they helped blacks 75 percent of the time. Whites helped both whites and blacks 44 percent of the time.

*(Cross-cultural research seems particularly rele­vant to the topic of helping in that Jesus' point in the parable of the "Good Samaritan" was that cultural enemies, Jews and Samaritans, should love and help each other)*

### Altruism & Religion {-}

The study of altruism or helping behavior also yields some interesting results with regard to the effects of religion. Research has consistently found that only a minority of people will stop to help someone who is clearly in need, especially if they are in a hurry themselves. Darley and Batson (1973) found that this was true even for seminary students, and *even when they were on their way to give a talk on the Good Samaritan.* Furthermore, they found that the most "religiously devout" were the least sensitive to the victims needs; when they did offer help, they often forced it on the victim even when he or she insisted on being left alone. Batson and Gray (1981) also found that the religiously devout tended to offer help when it was not wanted. Apparently if religion makes a difference it is not always good.

On the other hand, it should be noted that although only a minority of the seminarians stopped to help, they were *all* on their way to help the experimenter by giving a talk. Thus it was not a matter of helping or not, but a choice between which to help. If they stopped, they were led to believe, they would be late, and might endanger their ability to be of help to the experimenter.

In another setting, Perry London (1970) found Christian teaching often played a role in the justification given by those who helped hide Jews from the Nazis during World War II. Further research is needed before the role of religiousness in helping behavior can be determined. *(adapted from Psychology and Christianity by Ronald Philipchalk, pp. 219-220)*

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

What is it that makes you think that someone is attractive, kind, evil, competent, upset, and the like? These resources will look at some of the factors that contribute to how you judge others and yourself. The first article outlines some of the ways your face has shaped your social experiences. The second article adds to this discussion by looking at how willing people are to acknowledge the role of attractiveness in their own thought processes and decision-making. Next, the topic shifts to altruism. The first of these articles proposes that only reciprocal altruism exists. Again, I would encourage you to read this article through the lens of, *“Is it truly possible to know another’s motivation or intention?”* Lastly, Random Acts of Kindness is a website that offers great resources and opportunities to increase kindness in your, and others, lives. I encourage you to participate in some of these activities to see how it makes you feel. Click on the links below:

 - [**Facial Attractiveness**](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3130383/){target="_blank”}  
 - [**Survival of the Prettiest**](https://www.macleans.ca/society/science/the-mysterious-power-of-attractive-people/){target="_blank”}  
 - [**Altruism in Advertising**](https://public.wsu.edu/~taflinge/altruism.html){target="_blank”}  
 - [**Random Acts of Kindess**](http://www.actsofkindness.org/){target="_blank”}  

<span class="blockhead">Key Terms Quiz</span>

In order to review some of the major terms from Chapter 13 in your textbook, take the following unmarked quiz. Although you will not be evaluated on these terms, they will assist you in the assessments for this course. Type the correct answer in the boxes below:

[h5p id="89"]

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***What do you think contribute to you being able to quickly judge whether or not you think someone is attractive?***  
- ***Some social psychologists believe that there is always a reward for helping and that this motivates people to help. In other words, people never help without expecting a reward of some kind (either in this life or in the next). What do you think?***  

```

## Assessment {-}

```{block2, type='assessment'}

While there is no "formal" assignment that you will be responsible for submitting for Unit 7, you will be expected to participate in discussion during your Learning Lab. Your facilitator will be providing a participation mark based on your contributions. Below is some information to consider prior to attending your Learning Lab:

<span class="blockhead">Learning Lab Preparation</span>

Your facilitator will be providing a participation mark based on your contributions for this unit. Below is some information to consider prior to attending your Learning Lab:

*Active participation in group exercises, reflection, and critical discourse is an essential component of this course. You are expected to show respect for all members of the course, both in your speech and actions. Contribute by actively observing and listening, raising thoughtful questions, examining relevant issues, building on others’ ideas, analyzing and evaluating the group’s thinking, synthesizing key points, and expanding the group’s perspectives. Take care not to dominate a conversation, giving space for others to speak. When in small groups help maintain the focus, flow, and quality of conversations, and take the initiative to invite others (particularly those who are quiet) to speak.*

**Rubric for Participation in Learning Labs**

| Emerging (0-64%) | Developing (65-89%) | Mastering (90-100%)|
| -| -|-|
|Never to almost never: Demonstrates active listening (as indicated by disengaged body language and no to rare comments that build on others’ remarks), Initiates any contributions in class or small groups,  Makes insightful or constructive comments,  Helps maintain a supportive space for others to speak.|Sometimes to fairly often: Demonstrates active listening (as indicated by somewhat to often engaged body language and comments that build on others’ remarks),  Initiates a contribution at least once in a class or small group discussion;  Makes insightful or constructive comments,  Helps maintain a supportive space for others to speak.|Very often to nearly always: Demonstrates active listening (as indicated by fully engaged body language and comments that build on others’ remarks),  Initiates more than one contribution in a class or small group discussion,  Makes insightful or constructive comments,  Creates a space for others to speak and takes initiative to include others.|

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Define the key terminology associated with social influence, social cognition, and on attitudes, behaviour, and effective communication.  

- Describe why individuals conform to others’ behaviours, how individuals and groups can influence behaviours, and how we form first impressions and how these impressions influence us.  

- Apply your knowledge of the bystander effect to ensure that you will be helped if you are in an emergency, of social cognition to help overcome prejudice and discrimination, and of the central route to describe how a message should be designed.  

- Analyze whether guards who participate in abuse are inherently bad people, or if their behaviour is the product of social influences and whether people who commit discriminatory acts are necessarily prejudiced.  

- Describe how behaviours influence attitudes in terms of cognitive dissonance theory.  

```
