# Stress and Coping

## Overview {-}

In Unit 9, you will gain more insight into stress and coping. Together, Units 8 and 9 span information from Chapter 14 in your textbook, giving you a broad overview of the field of health psychology.

Health psychologists study both positive and negative impacts that humans’ behaviour and decisions have on their health, survival, and well-being. The need for this field has increased considerably over the 20th century, as most premature deaths are attributable to lifestyle factors. Over this chapter you will gain knowledge about the interaction of all the levels of analysis (biological, psychological, sociocultural, and spiritual) with regards to your health. You will learn about the biological/physiological responses to stress and how a poor response to stress leaves a person more vulnerable to illness and slowing recovery time from illness and injury.

You will also see how having at least some degree of control helps people with coping and outlook. When control is threatened, people use compensatory responses, such as detecting order within random images. You will also be informed that coping, using a positive or negative style, is related to personality (e.g., optimism versus pessimism). Positive coping increases resilience—the ability to recover from adversity, and even benefit from the experience, as is the case with post-traumatic growth. Whereas, coping via negative affectivity and pessimism can have both psychological and physiological disadvantages. Finally, you will be advised as to how religion/spirituality, relaxation techniques, meditation, and biofeedback actually help people cope with stress and problems which can lead to human flourishing.

### Topics {-}

This unit will be divided into the following topics:

1. Stress  
2. Health Psychology  

### Learning Outcomes {-}

By the end of this unit, student's will be able to:

- Define, and apply, the key terminology related to health psychology, stress and illness, and coping and well-being.  
- Describe how genetic and environmental factors influence obesity, how physiological reactions that occur under stress, and how the immune system is connected to stress responses.  
- Apply your knowledge of persuasion and health to examine the effectiveness of different types of cigarette warnings, and of the beneficial effects of optimism to help you reframe stressful situations as positive opportunities.  
- Analyze whether media depictions of smoking affect smoking in adolescents, the claim that ulcers are caused by stress, and whether activities such as relaxation techniques, meditation, and biofeedback actually help people cope with stress and problems.  
- Describe how control over the environment and positive and negative styles of coping influences well-being.  

### Activity Checklist {-}

```{block2, type='reflect'}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work:

<!-- [plugin:content-inject](_schedule) -->

<span class="blockhead">Read and Reflect</span>

- Read *Krause et al. (2021). Revel for An Introduction to Psychological Science, 3rd Canadian Edition*  
//todo #6
- Review [*Unit 9 - Slides*](PSYC106-CH14HealthStressandCoping3rdEd.pptx)  

*Please note, the slides are intended to supplement the information found in your textbook. If you are having trouble viewing them, they can also be downloaded by scrolling to the bottom of the screen and clicking on the "Unit 9 - Slides" link.*

<span class="blockhead">Personal Reflection</span>

If you are like most people, you likely have experienced some form of relational stress. Three common ways of handling this form of stress are to become aggressive, submissive, or assertive. In this activity, you look these different interpersonal conflict responses and determine what kind of outcome will likely follow a particular approach.

<span class="blockhead">Watch, Read, and Reflect</span>

In this activity you will watch Dr. Kelly McGonigal use some groundbreaking research to help people transform their perspective on stress. This just over 14 minute TED talk could actually change the course of your life. The second resource looks critically at the widely held belief that humour is good for your health.  

<span class="blockhead">Key Terms Quiz</span>

**NOTE:** *Units 8 & 9 both covered content from Chapter 14 in your textbook - this quiz will also cover terms from both units.*

- Practice quiz to assess how well you know key terms from Chapter 14.  
- Not for formal evaluation.  

<span class="blockhead">Learning Lab Preparation</span>

- Each topic will provide a question or scenario for you to consider prior to attending your Learning Lab. Be sure to carefully consider each prompt as you will be expected to contribute to the group discussion.  

<span class="blockhead">Assessment</span>

At the end of this unit, not only will you be assessed on your participation during the Learning Lab discussions, but you will also be responsible for submitting your first writing assignment.

- ***Writing Assignment #2*** is outlined on the "Assessment" page - expectations for this assignment, as  well as a grading rubric, can be found by clicking on that tab.  

- After completing this assignment, you will also be expected to completed ***Quiz #2.*** Again, information about the quiz can be found by clicking on the "Assessment" tab.  

```

### Resources {-}

Here are the resources you will need to complete this unit:

- Krause, M., Corts, D., Smith, S. C., & Dolderman, D. (2018). *Revel for An Introduction to Psychological Science, 2nd Canadian Edition.* Pearson Ed.  
- Other resources will be provided online.  

## Stress

Many health professionals and researchers have devised scales to measure stress. For some of these you might check out:

- [***Teach Health***](http://www.teachhealth.com/#stressscale){target="_blank”}  

This site also contains useful information on stress. Stress is a popular topic, so you will find lots of information on the internet; for example, you can find tips on reducing stress at:

- [***Ways to Reduce Mental Health Challenges***](http://www.ehow.com/how_3830_reduce-stress-life.html){target="_blank”}  

Many experts suggest meditation as a way to reduce stress. If you would like to investigate the topic of Christians and meditation further, I would encourage you to look into the Insight Timer app at:

- [***Insight Timer***](https://insighttimer.com/meditation-topics/christianity){target="_blank”}  

Insighttimer.com also has some excellent general meditation resources for improving one’s health over a number of different domains.

## Aggression, Submission, and Assertion

Much of the stress we experience comes from problems we have with other peo¬ple. Unfortunately, many people see only two alternatives in dealing with interper¬sonal conflict: aggression or submission. Are there other ways?
Assertiveness represents a third alternative but one that is often confused with aggression. Assertive statements are not attacks. Rather, they communi¬cate one's own perceptions and emotions. Such responses often take the form of "***I-statements***": I feel _________ when you do _________. Being assertive tends to defuse conflict situations because it gives both parties more complete information to work with—so it helps alleviate stress.

<!-- [plugin:content-inject](_activities) -->

### Activity: Personal Reflection {-}

```{block2, type='reflect'}


Now that you have some understanding concerning the differences between aggression, submission, and assertion, look at the situations below and devise all three kinds of responses to each one. Share these in your Learning Lab/Forum.

***Situation #1:*** *Someone is crowding in front of you in line at the grocery store.*

- Aggressive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Submissive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Assertive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  

***Situation #2:*** *After a physical exam the doctor gives you a prescription without telling you what the diagnosis is, what the medicine is for, or what the side effects might be. When you ask for this information, the doctor brushes off your question.*

- Aggressive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Submissive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Assertive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  

***Situation #3:*** *A boyfriend or girlfriend wants to end your relationship.*

- Aggressive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Submissive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Assertive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  

***Situation #4:*** *The boss tells you that your work has been of poor quality and that you will shape up or be fired.*

- Aggressive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Submissive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Assertive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  

***Situation #5:*** You have received a grade that is much lower than you feel you deserved on an essay examination.*

- Aggressive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Submissive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  
- Assertive Response: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  

Finally, in your forum, comment/respond on the following:

- ***Are any of your responses affected by your religious beliefs? How so?***

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***Each of us has some minor annoyances that add to our stress level more than they should. What gets you stressed out? What are your everyday "pet peeves" (annoyances)? Does the stress that these things produce seem justified? What are some things you can do to decreases your stress responses to these situations?***

```

## Health Psychology

As mentioned in the Overview, health psychologists study both positive and negative impacts that humans’ behaviour and decisions have on their health, survival, and well-being. Below are a couple of examples describing the impact of having some form of reward that perpetuates the use of a behaviour (whether healthy or unhealthy) and the power of remaining committed to making the changes you want to see.

1. A primary concern of health psychology is not to find new cures, but to get peo­ple to use the solutions that are available. Smoking, drug use, overeating, and gambling are just some of the destructive behaviors in which people engage be­cause they say they don't have the willpower to quit. We might say because they want to engage in them. Why? Generally, we have to conclude that there are rewards for engaging in these behaviors. You might want to examine some of your behaviors, especially ones that could be considered "maladaptive", in light of what rewards are maintaining them.  

2. E. Scott Geller has written extensively in the area of motivating healthful behav­ior. His research covers alcohol use, driving while impaired, highway safety, and seat belt use. For several years he has personally carried on a campaign to get air­lines to make a seat belt announcement at the end of each flight (Geller, 1989). Sometime during the flight Geller gives a pilot or flight attendant a small card.  

In addition to attractive graphics, the card contains the following message:

***Airline Announcement*** - *Now that you have worn a seat belt for the safest part of your trip, the flight crew would like to remind you to buckle-up during your ground transportation.*

Geller reports that in one 4 1/2 year time period, for 33.7 percent of the flights on which he gave out this card, the requested announcement was made. Some air­lines even made the buckle-up reminder a regular part of their end-of-flight an­nouncements. On the other hand, one airline distributed a memo to its staff stating "ignore the request of the Virginia Tech professor with the blue card." Geller had his cards reprinted on yellow stock and continued to distribute the requests! *Geller, E. S. (1989). The airline lifesaver: In pursuit of small wins. Journal of Applied Behavior Analysis, 22(3)*

This summary of Geller’s past activities demonstrates that with motivation and persistence, you can change not only your own behaviours, but also, those of large corporations. If you have been on an airplane recently, you have likely noticed that the universally communicated announcement to have your seatbelt fastened during landing and transport back to the terminal.

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

In this activity you will watch Dr. Kelly McGonigal’s *TED talk* titled, ***"How to Make Stress your Friend."***  This video is groundbreaking research to help people transform their perspective on stress:

<div style='max-width: 640px'><div style='position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;'><iframe width="640" height="360" src=https://embed.ted.com/talks/lang/en/kelly_mcgonigal_how_to_make_stress_your_friend" allowfullscreen style="border:none; position: absolute; top: 0; left: 0; right: 0; bottom: 0; height: 100%; max-width: 100%;"></iframe></div></div>

After watching the video, take a few minutes to read about Dr. Gil Greengross’ research that challenges the widely held belief that humour is good for your health. Here is the link to his Psychology Today article:

- [***Psychology Today***](https://www.psychologytoday.com/intl/blog/humor-sapiens/201805/humor-may-not-be-so-good-your-health){target="_blank”}  

Take some time to ponder the messages in these resources. The questions during Learning Lab will challenge you and your thoughts around the above sources.

<span class="blockhead">Key Terms Quiz</span>

In order to review some of the major terms from Chapter 14 in your textbook, take the following unmarked quiz. Although you will not be evaluated on these terms, they will assist you in the assessments for this course.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=83" width="936" height="706" frameborder="0" allowfullscreen="allowfullscreen" title="Psych 106 - Unit 9 Quiz"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***Who is ultimately responsible for how you react to different situations and circumstances in your life? How do you know this?***  
- ***Is there a good time to just laugh something off?***  
- ***What are some potential stress related consequences of habitually turning to humour when dealing with stress?***  

```

## Assessment {-}

```{block2, type='assessment'}

In addition to your participation in this unit's Learning Lab, you will also be responsible for two formal assessments. The first, is your **Writing Assignment #2** - more information can be found on this assignment by scrolling down the page. The second assessment that will take place is your second quiz - again, more information can be found by scrolling down the page.

*Active participation in group exercises, reflection, and critical discourse is an essential component of this course. You are expected to show respect for all members of the course, both in your speech and actions. Contribute by actively observing and listening, raising thoughtful questions, examining relevant issues, building on others’ ideas, analyzing and evaluating the group’s thinking, synthesizing key points, and expanding the group’s perspectives. Take care not to dominate a conversation, giving space for others to speak. When in small groups help maintain the focus, flow, and quality of conversations, and take the initiative to invite others (particularly those who are quiet) to speak.*

**Rubric for Participation in Learning Labs**

| Emerging (0-64%) | Developing (65-89%) | Mastering (90-100%)|
| -| -|-|
|Never to almost never: Demonstrates active listening (as indicated by disengaged body language and no to rare comments that build on others’ remarks), Initiates any contributions in class or small groups, Makes insightful or constructive comments,  Helps maintain a supportive space for others to speak.| Sometimes to fairly often: Demonstrates active listening (as indicated by somewhat to often engaged body language and comments that build on others’ remarks), Initiates a contribution at least once in a class or small group discussion;  Makes insightful or constructive comments,  Helps maintain a supportive space for others to speak.| Very often to nearly always: Demonstrates active listening (as indicated by fully engaged body language and comments that build on others’ remarks), Initiates more than one contribution in a class or small group discussion, Makes insightful or constructive comments, Creates a space for others to speak and takes initiative to include others.


## Writing Assignment #2

Your second writing assignment for the course will involve reading a formal research article and extracting important information. Research articles play an important role in the field of psychology as they present new findings and research that help us better understand the subject field. It is critical, however, to understand what information is important as we assess the value of the article we are reading. This assignment attempts to help us better understand those considerations.

Prior to moving ahead, it is strongly encouraged that you take a moment to review the [**How to Read Empirical Articles**](assets/unit_9/Assessment_Empirical_Short.pdf){target="_blank”} reading from the first writing assignment - this will serve as a reminder *why* you are reading an article so you can better understand *what* is important to get out of it.

Building upon that, also take some time to review [**How to Read a Journal Article in Social Psychology**](assets/unit_9/Assessment_Empirical_Long.pdf){target="_blank”} - this article will help support your understanding of formal, empirical research journal articles.

### Finally {-}

After reviewing the resources above, we begin this assignment by reading the following article:

[**Pathways Linking Early Socioeconomic Adversity to Diverging Profiles of Romantic Relationship Dissolution in Young Adulthood**](assets/unit_9/Romantic_Relationship_Dissolution_in_Young_Adulthood.pdf){target="_blank”}

<!-- [plugin:content-inject](_alert) -->

### Rubric for Writing Assignment #2 {-}

In addition to the criteria included in the rubric below, it is expected that students submit their assignments with an APA style title page.

 Estimate that each response will be between one paragraph to ½ a page (depending on what the question is asking and how much information is in the article). The total amount of content will be between 2 ½ to 3 pages (not including the title page).

| **Exceeds Expectations** | **Meets Expectations**          | **Minimally Meets Expectations**           | **Does Not Meet Expectations**                 |
||--|--|-|
|Responses are accurate and address the questions in a comprehensive manner     |Responses are accurate  and address the questions but could demonstrate more meaningful comprehension  of content     |Responses may lack accuracy in addressing the questions and/or may demonstrate limited comprehension of content     | Responses do not  accurately address the questions or do not demonstrate any comprehension of content   |
|Clear, precise and well-reasoned responses     |Mostly clear, precise and well-reasoned responses              |Some clear, precise and well-reasoned responses        |Responses lack clarity, logic and/or precision              |
|    |Spelling and grammar are accurate.                 |Minor and/or few spelling or grammatical errors.       | Several spelling or grammatical errors.      |

***To submit your completed assignment, scroll to the bottom of the page and click on the "Writing Assignment #2" tab - follow the directions there.***

### **Quiz #2** {-}

Upon completing your Writing Assignment #2, you will next complete your second quiz.

Your instructor will provide additional instructions. Student's will be provided with one attempt. You will be provided information about when the quiz will open so you can begin.

***To begin your quiz,*** click on the **Quiz #2** tab at the bottom of the screen.

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Define and apply the key terminology related to health psychology, stress and illness, and coping and well-being.  

- Describe how genetic and environmental factors influence obesity, how physiological reactions that occur under stress, and how the immune system is connected to stress responses.  

- Apply your knowledge of persuasion and health to examine the effectiveness of different types of cigarette warnings, and of the beneficial effects of optimism to help you reframe stressful situations as positive opportunities.  

- Analyze whether media depictions of smoking affect smoking in adolescents, the claim that ulcers are caused by stress, and whether activities such as relaxation techniques, meditation, and biofeedback actually help people cope with stress and problems.  

- Describe how control over the environment and positive and negative styles of coping influences well-being.  

```
