# Final Assessments

As mentioned in the previous units, student's will be responsible for completing two final formal assessment. This page will provide an outline of what is expected for your Term Paper.

## Assignment Overview {-}

As Christians and as psychologists, it is crucial that we are able to critically evaluate psychological research. The main purpose of this assignment is to provide you with an opportunity to utilize your skills in research design and analysis as well as to practice your interpretation and critical analysis skills. You will also begin to utilize formatting guidelines specific to an academic discipline. In this case, you will use those provided by the American Psychological Association (APA).

## Term Paper

The first of your final assessments will be to submit a term paper. This term paper will require you to call upon information you have learned throughout the entire course - in particular, this term paper will continue to build upon the skills you applied in writing your **Writing Assignment #1** and **Writing Assignment #2** submissions. Additional resources will be provided at the bottom of this page - they are intended to support the development of your paper.

### STEP 1: Choose an Article {-}

Select one of the following topics from the course. Topics include language development, social roles and obedience, ADHD & Autism, emotional intelligence, and cognitive behavioral therapy. You should familiarize yourself with the topic by browsing through the textbook and lecture notes (if we have already covered it in class).
You should then search for a journal article of interest to you that falls within this topic. You should identify this article as being either a true experiment or a non-experiment. Using *PSYCInfo* via the TWU library website, use keywords to search for articles. More details on how to do this will be provided in class. Choose articles that you find interesting and are able to understand. Some articles can be jargon-filled and complicated, so it is in your best interest to choose one that you will be able to read and write about.

### STEP 2: Summarize Your Article {-}

After reading the article, you should begin to summarize the main points. Just as you would describe the study if you were having a casual conversation with someone, you should summarize the study so that it is brief and easy to understand. You should summarize the article in your own words. Copying sections from the article is considered to be plagiarism. A description of each section of an article is provided below:

*Introduction*

In their introduction, the author(s) will describe previous research. In your summary indicate the main findings of that previous research. Additionally, in the introduction the author(s) will describe the purpose of the study they conducted and how it relates to the previous research. In your summary you should identify the question that the author(s) were trying to answer and the hypotheses they were evaluating.`

//todo #9
### Activity Checklist {-}

```{block2, type='reflect'}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work:


<span class="blockhead">Read and Reflect</span>

- Read *Krause et al. (2021). Revel for An Introduction to Psychological Science, 3rd Canadian Edition*  

//todo #10
- Review [*Unit 12 - Slides*](PSYC106-CH16Therapies3rdEd.pptx)

*Please note, the slides are intended to supplement the information found in your textbook. If you are having trouble viewing them, they can also be downloaded by scrolling to the bottom of the screen and clicking on the "Unit 12 - Slides" link.*

- This activity gives you an opportunity to explore the American Psychological Association website. In many ways, the APA leads the discipline and profession of psychology. It is an excellent resource for finding information on a number of areas of psychology, contemporary issues in psychology, a plethora of resources for self-help. They also have the opportunity for students to become student affiliates and enjoy member privileges that will contribute to your development as a professional.  

- It is important when considering biological treatments to receive input from more than one professional and to do adequate research on the treatment to understand the potential risks and benefits. This activity serves as a resource for electroconvulsive therapy (ECT), transcranial magnetic stimulation (TMS), and vagus nerve stimulation (VNS) as treatments for depression. It also has a link to explore an alternative therapy known as neurotherapy/neurofeedback, which is a safe (when administered by a well-trained professional), non-invasive option for a number of different developmental and psychological matters.  

- Looking intently at how you are spending your time and taking preventative steps to contribute to your mental/emotional health and overall well-being is a great gift to give to yourself (and ultimately others). This activity offers a resource where you can find information on a variety of (usually research-based) preventative strategies. Moreover, if you decide that you would like to explore therapy for yourself, there are resources here to inform you as to how to find a suitable therapist and what some of your rights and responsibilities are in therapy.  

<span class="blockhead">Learning Lab Preparation</span>

- Each topic will provide a question or scenario for you to consider prior to attending your Learning Lab. Be sure to carefully consider each prompt as you will be expected to contribute to the group discussion.  

<span class="blockhead">Final Assessments</span>

- As mentioned, each student will be responsible for submitting a Term Paper, as well as completing a Final Exam. More information can be found by clicking on the **"Final Assessment"** tab at the top of the screen.  

```

## Evaluating Therapy

### Therapy? {-}

In a previous chapter, we looked at various ways of understanding personality. In the first part of this chapter we have been considering different therapies that grow out of these personality theories. Now it is time to ask the question, “Does it work? Is psychotherapy effective?” The answer seems to be “Yes,” but there are qualifications. First, many people who do not receive treatment get better anyway. And second, placebo treatments also produce improvements, as do non-professional caring relationships. As David Myers says,


*“All types of psychotherapy seem to offer three benefits: new hope, a fresh perspective, and an empathic, trusting, caring relationship.” (p. 592)*

When you stop and think about it, isn't this what a good friend offers? Maybe if we all experienced (and offered) this kind of friendship, therapists wouldn’t be so much in demand.

### Therapy in Other Cultures {-}

The process of psychotherapy generally assumes a cultural value of sharing your inner feelings and problems with another individual. David Ho observes that in the culture of Hong Kong, it is a sign of weakness to talk about one's problems and to reveal much of one's self. This cultural background influences the style of therapy and the process of psychotherapy. How would you proceed if you were a therapist?

Paul Pedersen (1985; 1987; 2000) suggests that we do not need to look at cultures outside North America to see differences in the process of psychotherapy. He sug­gests that different sub cultural minorities within North America approach psy­chotherapy with different values and different expectations. Native North American cultures, Asian immigrants, Hispanics, and Afro-Americans have different approaches to the pro­cess of psychotherapy. A therapist needs to be aware of these cultural differ­ences to perform effectively in the therapeutic situation.

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

As mentioned earlier, this activity gives you an opportunity to explore the American Psychological Association (APA) website. In many ways, the APA leads the discipline and profession of psychology. It is an excellent resource for finding information on a number of areas of psychology, contemporary issues in psychology, a plethora of resources for self-help. They also have the opportunity for students to become student affiliates and enjoy member privileges that will contribute to your development as a professional. Follow the link below:

- [**American Psychological Association**](https://www.apa.org/){target="_blank”}  

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

 - ***Do you think an empathic, trusting, caring friend could be as effective as a trained psychotherapist or counselor?***  

```

## Biological Treatments

Though there are a number of treatments options within the field of psychology, there are two basic treatment models:

1. The Wellness Model  
2. The Medical Model.  

The Wellness Model will look intently, and holistically, at a number of areas of a person’s life (thoughts/emotions, relationships, work/academics, developmental stage, nutrition, activity/leisure, and sleep, to name a few) and illuminate the client’s strengths and resources to help them find a way to overcome challenges and lead a more fulfilling life. Many of the psychotherapeutic approaches looked at, thus far, operate on this model.

The Medical Model, however,  is based on symptom recognition, (differential) diagnosis, prognosis, and often a pharmacological support and possibly an invasive or non-invasive procedure. The topic of biological treatments is based on the medical model.

### Medical Treatments {-}

Although psychotherapy in its various forms has grown in importance over the past generation, people are still more inclined to seek the help of medical professionals over mental health professionals for their psychological concerns. One of the greatest changes in the way we have treated psychological disorders has been through the discovery and use of various drugs. In this section, we consider the various biomedical therapies that are available for psychological disorders.

### Not a Panacea {-}

All of the biological therapies produce side effects, some of them permanent. Since the brain cannot regenerate itself, psychosurgery is irreversible; ECT destroys brain cells, producing memory loss, some of which is permanent; virtually all drugs have side effects besides the dependency produced, and some of these are permanent. (For example, one class of antipsychotic drugs, the phenothiazines, can produce a permanent and irreversible muscle disorder, particularly after massive long-term use. This disorder, called tardive dyskinesia, is evidenced by involuntary movements of the face, limbs, and trunk.) Furthermore, the unknown basis of the effects of many of these techniques (e.g., ECT, and some drugs), and the exploratory nature of others (psychosurgery) should make us at least a little skeptical. (A further controversy surrounding the use of physiological therapies, particularly, ECT, concerns their forced administration to involuntary patients.)

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

It is important, when considering biological treatments, to receive input from more than one professional and to do adequate research on the treatment to understand the potential risks and benefits. This activity serves as a resource for electroconvulsive therapy (ECT), transcranial magnetic stimulation (TMS), and vagus nerve stimulation (VNS) as treatments for depression. It also has a link to explore an alternative therapy known as neurotherapy/neurofeedback, which is a safe (when administered by a well-trained professional), non-invasive option for a number of different developmental and psychological matters. To learn more, read below:

- [**Electroconvulsive Therapy and Other Depression Treatments**](https://www.webmd.com/depression/guide/electroconvulsive-therapy#1){target="_blank”}  

- [**International Society for Neuroregulation and Research**](https://isnr.org/){target="_blank”}  

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***As biological influence in psychological disorders becomes more obvious, what are the implications for psychologists and "talk therapy?”***  

- ***Will biological therapies eventually replace old style talk therapies?***  

```

## Preventing Problems

***A Little Help When You Need It...***

The textbook discusses the value of prevention on a broad level, including environmental changes. Here, we take a more personal look at how you might go about dealing with major problems or just simple blockages in your pathway to growth.

We all need help from time to time, whether we get it from family, friends, or paid professionals. Professional help can be a real boost. It might be testing to clarify career directions, sharing a relationship issue with a sympathetic listener, or in-depth study of a long-term problem. A trained helper provides an objective perspective and an empathic ear.

### An Ounce of Prevention {-}

Being aware of the possible causes of psychological problems as well as the appropriate treatments can help you avoid similar difficulties in your own life. For example you can:

- Not bury and deny strong emotions (psychodynamic view)  
- Take responsibility for your feelings & promote growth (humanistic view)  
- Associate positive consequences with desirable actions and negative results with undesirable ones (behavioral view)  
- Avoid negative self-talk in favor of positive (cognitive view)  
- Cultivate empathic, trusting, caring relationships  
- Take steps to ensure a healthy body  

<!-- [plugin:content-inject](_activities) -->

### Activity: Read and Reflect {-}

```{block2, type='reflect'}

Looking intently at how you are spending your time and taking preventative steps to contribute to your mental/emotional health and overall well-being is a great gift to give to yourself (and ultimately others). This activity offers a resource where you can find information on a variety of (usually research-based) preventative strategies. Moreover, if you decide that you would like to explore therapy for yourself, there are resources here to inform you as to how to find a suitable therapist and what some of your rights and responsibilities are in therapy.

- [**Psychology Help Center**](https://www.apa.org/helpcenter/){target="_blank”}  

- [**How to Choose a Therapist**](http://psychcentral.com/therapst.htm){target="_blank”}  

- [**Rights and Responsibilities in Psychotherapy**](Rights-and-Responsibilities-in-Psychotherapy.pdf){target="_blank”}  

<span class="blockhead">Learning Lab Preparation</span>

Prior to your Learning Lab, take some time to think about the following questions. You will be asked to share your thoughts in this week's Learning Lab:

- ***What role do your religious or other beliefs play in your efforts to avoid psychological difficulties and promote growth?***  

- ***Do your beliefs affect your choice of the kind of help you would look for?***  

```

## Assessment {-}

```{block2, type='assessment'}

In addition to your participation in this unit's Learning Lab, you will also be responsible for completing **Quiz #3** - more information can be found by scrolling down to the bottom of the page.

*Active participation in group exercises, reflection, and critical discourse is an essential component of this course. You are expected to show respect for all members of the course, both in your speech and actions. Contribute by actively observing and listening, raising thoughtful questions, examining relevant issues, building on others’ ideas, analyzing and evaluating the group’s thinking, synthesizing key points, and expanding the group’s perspectives. Take care not to dominate a conversation, giving space for others to speak. When in small groups help maintain the focus, flow, and quality of conversations, and take the initiative to invite others (particularly those who are quiet) to speak.*

**Rubric for Participation in Learning Labs**

| Emerging (0-64%) | Developing (65-89%) | Mastering (90-100%)|
| -| -|-|
|Never to almost never: Demonstrates active listening (as indicated by disengaged body language and no to rare comments that build on others’ remarks),Initiates any contributions in class or small groups, Makes insightful or constructive comments, Helps maintain a supportive space for others to speak.|Sometimes to fairly often: Demonstrates active listening (as indicated by somewhat to often engaged body language and comments that build on others’ remarks), Initiates a contribution at least once in a class or small group discussion; Makes insightful or constructive comments, Helps maintain a supportive space for others to speak.|Very often to nearly always: Demonstrates active listening (as indicated by fully engaged body language and comments that build on others’ remarks), Initiates more than one contribution in a class or small group discussion, Makes insightful or constructive comments, Creates a space for others to speak and takes initiative to include others.

<span class="blockhead">Quiz #3</span>

Your instructor will provide additional instructions. Student's will be provided with one attempt. You will be provided information about when the quiz will open so you can begin.

***To begin your quiz,*** click on the **Quiz #3** tab at the bottom of the screen.


**REMEMBER:** *You are also responsible for two final assessments found on the "Final Assessments" page*

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, check that you are able to:

- Define, and apply, the key terminology related to health psychology, stress and illness, and coping and well-being.  

- Describe how genetic and environmental factors influence obesity, how physiological reactions that occur under stress, and how the immune system is connected to stress responses.  

- Apply your knowledge of persuasion and health to examine the effectiveness of different types of cigarette warnings, and of the beneficial effects of optimism to help you reframe stressful situations as positive opportunities.  

- Analyze whether media depictions of smoking affect smoking in adolescents, the claim that ulcers are caused by stress, and whether activities such as relaxation techniques, meditation, and biofeedback actually help people cope with stress and problems.  

- Describe how control over the environment and positive and negative styles of coping influences well-being.  

```
